irrigation:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: irrigation.duckdb
      threads: 4
      extensions:
        - httpfs
      settings:
        s3_endpoint: "{{ env_var('S3_ENDPOINT_HOST', 'localhost:9000') }}"
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
        s3_url_style: "path"
        s3_use_ssl: false
        s3_region: "us-east-1"