# ---- Écoute ----
listener 1883
protocol mqtt

# ---- Authentification ----
allow_anonymous false
password_file /mosquitto/config/passwd

# ---- Persistance ----
persistence true
persistence_location /mosquitto/data/
autosave_interval 60

# ---- Logs ----
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true